package report;

import java.util.List;
import java.util.Objects;

// The specification. Read this first, then make every test pass. Do not edit this file.
// Run it with:  javac report/*.java  &&  java report.RunTests    (or run.cmd / run.sh)
public class RunTests {

    public static void main(String[] args) {

        // --- the two formats produce exactly the right text --------------------------------
        check("csv puts the title on line one, then each row", () ->
            expectEquals("""
                            Sales
                            a
                            b""",
                new CsvFormat().format(new Report("Sales", List.of("a", "b")))));

        check("csv of an empty report is just the title", () ->
            expectEquals("Empty",
                new CsvFormat().format(new Report("Empty", List.of()))));

        check("json has a title and a rows array", () ->
            expectEquals("""
                            {"title":"Sales","rows":["a","b"]}""",
                new JsonFormat().format(new Report("Sales", List.of("a", "b")))));

        check("json of an empty report has an empty array", () ->
            expectEquals("""
                            {"title":"Empty","rows":[]}""",
                new JsonFormat().format(new Report("Empty", List.of()))));

        // --- DIP: the service uses whatever format it was given, nothing else --------------
        check("the service delegates to the format it was injected with", () -> {
            Report r = new Report("Sales", List.of("a", "b"));
            expectEquals(new CsvFormat().format(r), new ReportService(new CsvFormat()).export(r));
        });

        // --- SRP: validation lives in the service, not the formatter -----------------------
        check("the service rejects a blank title", () ->
            expectThrows(IllegalArgumentException.class, () ->
                new ReportService(new CsvFormat()).export(new Report("   ", List.of("a")))));

        // --- OCP + DIP: a brand new format works with the UNCHANGED service -----------------
        check("the service accepts a new format it has never seen", () -> {
            ReportFormat plain = report -> "plain:" + report.title();   // a format defined right here
            expectEquals("plain:Sales",
                new ReportService(plain).export(new Report("Sales", List.of("a"))));
        });

        // --- LSP + ISP: every format is substitutable through the one interface ------------
        check("all formats are interchangeable behind the interface", () -> {
            Report r = new Report("Q", List.of("x"));
            for (ReportFormat f : List.of(new CsvFormat(), new JsonFormat())) {
                String out = new ReportService(f).export(r);
                if (out == null || out.isEmpty())
                    throw new AssertionError("empty output from " + f.getClass().getSimpleName());
            }
        });

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        if (failed > 0) System.exit(1);
    }

    // --- a tiny test harness. No JUnit, no Maven, nothing to download. ---------------------
    interface Body { void run() throws Throwable; }
    static int passed = 0, failed = 0;

    static void check(String name, Body body) {
        try {
            body.run();
            passed++;
            System.out.println("  PASS  " + name);
        } catch (Throwable t) {
            failed++;
            System.out.println("  FAIL  " + name + "  ->  " + t);
        }
    }

    static void expectEquals(Object expected, Object actual) {
        if (!Objects.equals(expected, actual))
            throw new AssertionError("expected [" + expected + "] but was [" + actual + "]");
    }

    static void expectThrows(Class<? extends Throwable> type, Body body) {
        try {
            body.run();
        } catch (Throwable t) {
            if (type.isInstance(t)) return;
            throw new AssertionError("expected " + type.getSimpleName() + " but threw " + t);
        }
        throw new AssertionError("expected " + type.getSimpleName() + " but nothing was thrown");
    }
}
