package editor;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

// The specification. Read this first, then make every test pass. Do not edit this file.
// Run it with:  javac editor/*.java  &&  java editor.RunTests   (or run-editor.cmd / .sh)
// EXPERT capstone - the seven patterns the cafe and theater capstones did NOT cover:
//   CP1 Command   CP2 Memento   CP3 State   CP4 Composite
//   CP5 Iterator  CP6 Visitor   CP7 Chain of Responsibility
public class RunTests {

    public static void main(String[] args) {

        System.out.println("-- CP1: Command (do / undo / redo) --");

        check("running commands builds up the text", () -> {
            Editor e = new Editor();
            e.run(new InsertText(e, "Hello"));
            e.run(new InsertText(e, " World"));
            expectEquals("Hello World", e.text());
        });

        check("undo peels off the last command, in order", () -> {
            Editor e = new Editor();
            e.run(new InsertText(e, "Hello"));
            e.run(new InsertText(e, " World"));
            e.undo();
            expectEquals("Hello", e.text());
            e.undo();
            expectEquals("", e.text());
        });

        check("redo replays what undo took back", () -> {
            Editor e = new Editor();
            e.run(new InsertText(e, "Hello"));
            e.run(new InsertText(e, " World"));
            e.undo();
            e.undo();
            e.redo();
            expectEquals("Hello", e.text());
            e.redo();
            expectEquals("Hello World", e.text());
        });

        check("a fresh command clears the redo trail", () -> {
            Editor e = new Editor();
            e.run(new InsertText(e, "a"));
            e.run(new InsertText(e, "b"));
            e.undo();                        // back to "a"
            e.run(new InsertText(e, "c"));   // "ac" - redo trail is now gone
            e.redo();                        // nothing to redo
            expectEquals("ac", e.text());
        });

        System.out.println("\n-- CP2: Memento (snapshot / restore) --");

        check("restore brings back a snapshot taken earlier", () -> {
            Editor e = new Editor();
            e.run(new InsertText(e, "draft one"));
            Memento saved = e.snapshot();
            e.run(new InsertText(e, " and two"));
            expectEquals("draft one and two", e.text());
            e.restore(saved);
            expectEquals("draft one", e.text());
        });

        check("an early snapshot restores an empty document", () -> {
            Editor e = new Editor();
            Memento start = e.snapshot();
            e.run(new InsertText(e, "typed something"));
            e.restore(start);
            expectEquals("", e.text());
        });

        System.out.println("\n-- CP3: State (editor modes) --");

        check("INSERT is the default mode and types characters", () -> {
            Editor e = new Editor();
            expectEquals("INSERT", e.mode());
            e.type('a');
            e.type('b');
            expectEquals("ab", e.text());
        });

        check("READONLY mode ignores keystrokes", () -> {
            Editor e = new Editor();
            e.type('a');
            e.type('b');
            e.setMode(new ReadOnlyMode());
            e.type('c');
            expectEquals("READONLY", e.mode());
            expectEquals("ab", e.text());
        });

        check("switching back to INSERT types again", () -> {
            Editor e = new Editor();
            e.type('a');
            e.setMode(new ReadOnlyMode());
            e.type('x');
            e.setMode(new InsertMode());
            e.type('b');
            expectEquals("ab", e.text());
        });

        System.out.println("\n-- CP4: Composite (document tree) --");

        check("a paragraph counts its own words", () -> {
            expectEquals(2, new Paragraph("hello world").wordCount());
            expectEquals(0, new Paragraph("   ").wordCount());
            expectEquals(1, new Paragraph("one").wordCount());
        });

        check("a section sums its children", () -> {
            Section s = new Section("doc").add(new Paragraph("a b")).add(new Paragraph("c d e"));
            expectEquals(5, s.wordCount());
        });

        check("nested sections roll up recursively", () -> {
            Section root = new Section("root")
                .add(new Paragraph("one"))
                .add(new Section("sub").add(new Paragraph("two three")).add(new Paragraph("four")));
            expectEquals(4, root.wordCount());
        });

        System.out.println("\n-- CP5: Iterator (walk the paragraphs) --");

        check("iterating yields every paragraph in document order", () -> {
            Section root = new Section("root")
                .add(new Paragraph("a b"))
                .add(new Section("sub").add(new Paragraph("c")).add(new Paragraph("d e f")));
            List<String> got = new ArrayList<>();
            for (Paragraph p : root) got.add(p.text());
            expectEquals(List.of("a b", "c", "d e f"), got);
        });

        check("a tree with no paragraphs iterates zero times", () -> {
            Section empty = new Section("root").add(new Section("sub"));
            List<String> got = new ArrayList<>();
            for (Paragraph p : empty) got.add(p.text());
            expectEquals(List.of(), got);
        });

        System.out.println("\n-- CP6: Visitor (new operation, nodes untouched) --");

        check("a visitor computes the same word count as the tree", () -> {
            Section root = new Section("root")
                .add(new Paragraph("one"))
                .add(new Section("sub").add(new Paragraph("two three")).add(new Paragraph("four")));
            WordCountVisitor v = new WordCountVisitor();
            root.accept(v);
            expectEquals(root.wordCount(), v.total());
            expectEquals(4, v.total());
        });

        check("a visitor works on a single leaf too", () -> {
            WordCountVisitor v = new WordCountVisitor();
            new Paragraph("x y z").accept(v);
            expectEquals(3, v.total());
        });

        System.out.println("\n-- CP7: Chain of Responsibility (text pipeline) --");

        check("the full pipeline trims, collapses spaces, then censors - in that order", () -> {
            TextFilter clean = TextFilter.chain(new TrimFilter(), new CollapseSpaces(), new Censor("badword"));
            expectEquals("hello world ***", clean.process("  hello    world  badword "));
        });

        check("a one-filter chain just runs that filter", () -> {
            expectEquals("a b c", TextFilter.chain(new CollapseSpaces()).process("a   b  c"));
        });

        check("the chain runs in the order you build it", () -> {
            TextFilter clean = TextFilter.chain(new TrimFilter(), new Censor("x"));
            expectEquals("hi ***", clean.process("  hi x  "));
        });

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        if (failed > 0) System.exit(1);
    }

    // --- a tiny test harness. No JUnit, no Maven, nothing to download. ---------------------
    interface Body { void run() throws Throwable; }
    static int passed = 0, failed = 0;

    static void check(String name, Body body) {
        try {
            body.run();
            passed++;
            System.out.println("  PASS  " + name);
        } catch (Throwable t) {
            failed++;
            System.out.println("  FAIL  " + name + "  ->  " + t);
        }
    }

    static void expectEquals(Object expected, Object actual) {
        if (!Objects.equals(expected, actual))
            throw new AssertionError("expected [" + expected + "] but was [" + actual + "]");
    }

    static void expectTrue(String what, boolean cond) {
        if (!cond) throw new AssertionError("expected " + what);
    }
}
