package theater;

import java.util.List;
import java.util.Objects;

// The specification. Read this first, then make every test pass. Do not edit this file.
// Run it with:  javac theater/*.java  &&  java theater.RunTests   (or run-theater.cmd / .sh)
// The tests are grouped into five checkpoints - make each green before moving on:
//   CP1 Builder   CP2 Singleton   CP3 Adapter   CP4 Facade   CP5 Template Method
public class RunTests {

    public static void main(String[] args) {

        System.out.println("-- CP1: Builder --");

        check("builder sets every part, and describe() reads them back", () -> {
            Scene s = Scene.builder("Movie").lights(10).volume(40).source("projector").build();
            expectEquals("Movie: lights 10%, volume 40, source projector", s.describe());
        });

        check("omitted parts fall back to sensible defaults", () -> {
            Scene s = Scene.builder("Reading").build();
            expectEquals("Reading: lights 100%, volume 20, source none", s.describe());
        });

        check("you can set just one part and leave the rest default", () -> {
            Scene s = Scene.builder("Dim").lights(30).build();
            expectEquals("Dim: lights 30%, volume 20, source none", s.describe());
        });

        System.out.println("\n-- CP2: Singleton --");

        check("Hub.get() hands back the very same instance every time", () ->
            expectTrue("Hub.get() == Hub.get()", Hub.get() == Hub.get()));

        check("the one hub remembers state across calls", () -> {
            int before = Hub.get().scenesRun();
            Hub.get().record("Alpha");
            expectEquals(before + 1, Hub.get().scenesRun());
            expectEquals("Alpha", Hub.get().lastScene());
        });

        System.out.println("\n-- CP3: Adapter --");

        check("adapter powers the vintage amp on through the SoundSystem interface", () -> {
            SoundSystem s = new AmpAdapter(new VintageAmp());
            s.on();
            expectEquals("amp[on, dial=0]", s.status());
        });

        check("adapter scales full volume (100) down to the amp's 0..11 dial", () -> {
            SoundSystem s = new AmpAdapter(new VintageAmp());
            s.on();
            s.setVolume(100);
            expectEquals("amp[on, dial=11]", s.status());
        });

        check("adapter scales a middling volume (50 -> dial 5)", () -> {
            SoundSystem s = new AmpAdapter(new VintageAmp());
            s.setVolume(50);
            expectEquals("amp[off, dial=5]", s.status());
        });

        System.out.println("\n-- CP4: Facade --");

        check("one watch() call drives the whole subsystem, in order", () -> {
            Scene scene = Scene.builder("Movie").lights(10).volume(40).source("projector").build();
            List<String> log = new Theater(new Lights(), new AmpAdapter(new VintageAmp()), new Screen()).watch(scene);
            expectEquals(List.of("lights -> 10%", "sound on", "volume 40", "screen -> projector"), log);
        });

        check("the facade actually changed each box behind the door", () -> {
            Lights lights = new Lights();
            SoundSystem sound = new AmpAdapter(new VintageAmp());
            Screen screen = new Screen();
            Scene scene = Scene.builder("Movie").lights(10).volume(40).source("projector").build();
            new Theater(lights, sound, screen).watch(scene);
            expectEquals(10, lights.level());
            expectEquals("projector", screen.showing());
            expectEquals("amp[on, dial=4]", sound.status());   // 40 percent -> dial 4
        });

        check("the facade records the scene on the one Hub", () -> {
            int before = Hub.get().scenesRun();
            new Theater(new Lights(), new AmpAdapter(new VintageAmp()), new Screen())
                .watch(Scene.builder("Doc").build());
            expectEquals(before + 1, Hub.get().scenesRun());
            expectEquals("Doc", Hub.get().lastScene());
        });

        System.out.println("\n-- CP5: Template Method --");

        check("projector runs the fixed skeleton with its own warm-up", () ->
            expectEquals(List.of("plugged in", "warming the bulb", "ready"), new Projector().startUp()));

        check("sound bar runs the SAME skeleton, a different hook", () ->
            expectEquals(List.of("plugged in", "instant on", "ready"), new SoundBar().startUp()));

        check("the skeleton is locked: same first and last, only the middle differs", () -> {
            List<String> p = new Projector().startUp();
            List<String> s = new SoundBar().startUp();
            expectEquals("plugged in", p.get(0));
            expectEquals("ready", p.get(2));
            expectEquals(p.get(0), s.get(0));
            expectEquals(p.get(2), s.get(2));
            expectTrue("only the warm-up hook differs", !p.get(1).equals(s.get(1)));
        });

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        if (failed > 0) System.exit(1);
    }

    // --- a tiny test harness. No JUnit, no Maven, nothing to download. ---------------------
    interface Body { void run() throws Throwable; }
    static int passed = 0, failed = 0;

    static void check(String name, Body body) {
        try {
            body.run();
            passed++;
            System.out.println("  PASS  " + name);
        } catch (Throwable t) {
            failed++;
            System.out.println("  FAIL  " + name + "  ->  " + t);
        }
    }

    static void expectEquals(Object expected, Object actual) {
        if (!Objects.equals(expected, actual))
            throw new AssertionError("expected [" + expected + "] but was [" + actual + "]");
    }

    static void expectTrue(String what, boolean cond) {
        if (!cond) throw new AssertionError("expected " + what);
    }
}
