package cafe;

import java.util.Objects;

// The specification. Read this first, then make every test pass. Do not edit this file.
// Run it with:  javac cafe/*.java  &&  java cafe.RunTests    (or run.cmd / run.sh)
public class RunTests {

    public static void main(String[] args) {

        // --- base drinks (given) ------------------------------------------------------------
        check("espresso is 200 cents, described Espresso", () -> {
            expectEquals("Espresso", new Espresso().description());
            expectEquals(200, new Espresso().cents());
        });

        check("tea is 150 cents, described Tea", () -> {
            expectEquals("Tea", new Tea().description());
            expectEquals(150, new Tea().cents());
        });

        // --- DECORATOR: an add-on wraps a drink and adds to both cost and description -------
        check("milk decorates espresso (+50, adds ', milk')", () -> {
            Beverage b = new Milk(new Espresso());
            expectEquals("Espresso, milk", b.description());
            expectEquals(250, b.cents());
        });

        check("decorators stack: syrup on milk on espresso", () -> {
            Beverage b = new Syrup(new Milk(new Espresso()));
            expectEquals("Espresso, milk, syrup", b.description());
            expectEquals(325, b.cents());
        });

        // --- FACTORY: build a base drink from its name --------------------------------------
        check("factory builds a drink from its name", () -> {
            Beverage b = new BeverageFactory().create("espresso");
            expectEquals("Espresso", b.description());
            expectEquals(200, b.cents());
        });

        check("factory rejects an unknown name", () ->
            expectThrows(IllegalArgumentException.class, () ->
                new BeverageFactory().create("boba")));

        // --- STRATEGY: swap the discount without changing anything else ---------------------
        check("no-discount strategy leaves the price alone", () ->
            expectEquals(500, new NoDiscount().applyTo(500)));

        check("percent-off strategy takes its cut", () ->
            expectEquals(400, new PercentOff(20).applyTo(500)));

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        if (failed > 0) System.exit(1);
    }

    // --- a tiny test harness. No JUnit, no Maven, nothing to download. ---------------------
    interface Body { void run() throws Throwable; }
    static int passed = 0, failed = 0;

    static void check(String name, Body body) {
        try {
            body.run();
            passed++;
            System.out.println("  PASS  " + name);
        } catch (Throwable t) {
            failed++;
            System.out.println("  FAIL  " + name + "  ->  " + t);
        }
    }

    static void expectEquals(Object expected, Object actual) {
        if (!Objects.equals(expected, actual))
            throw new AssertionError("expected [" + expected + "] but was [" + actual + "]");
    }

    static void expectThrows(Class<? extends Throwable> type, Body body) {
        try {
            body.run();
        } catch (Throwable t) {
            if (type.isInstance(t)) return;
            throw new AssertionError("expected " + type.getSimpleName() + " but threw " + t);
        }
        throw new AssertionError("expected " + type.getSimpleName() + " but nothing was thrown");
    }
}
