package cafe;

import java.util.Objects;

// The specification. Read this first, then make every test pass. Do not edit this file.
// Run it with:  javac cafe/*.java  &&  java cafe.RunTests    (or run.cmd / run.sh)
// The tests are grouped into four checkpoints - make each green before moving on:
//   CP1 Factory & base drinks   CP2 Decorator   CP3 Strategy   CP4 Observer
public class RunTests {

    public static void main(String[] args) {

        System.out.println("-- CP1: Factory & base drinks --");

        check("espresso is 200 cents, described Espresso", () -> {
            expectEquals("Espresso", new Espresso().description());
            expectEquals(200, new Espresso().cents());
        });

        check("tea is 150 cents, described Tea", () -> {
            expectEquals("Tea", new Tea().description());
            expectEquals(150, new Tea().cents());
        });

        check("factory builds a drink from its name", () -> {
            Beverage b = new BeverageFactory().create("espresso");
            expectEquals("Espresso", b.description());
            expectEquals(200, b.cents());
        });

        check("factory is forgiving about case and spacing", () -> {
            Beverage b = new BeverageFactory().create("  Espresso ");
            expectEquals("Espresso", b.description());
            expectEquals(200, b.cents());
        });

        check("factory rejects an unknown name", () ->
            expectThrows(IllegalArgumentException.class, () ->
                new BeverageFactory().create("boba")));

        System.out.println("\n-- CP2: Decorator --");

        check("milk decorates espresso (+50, adds ', milk')", () -> {
            Beverage b = new Milk(new Espresso());
            expectEquals("Espresso, milk", b.description());
            expectEquals(250, b.cents());
        });

        check("the same decorator works on any drink (milk on tea)", () -> {
            Beverage b = new Milk(new Tea());
            expectEquals("Tea, milk", b.description());
            expectEquals(200, b.cents());
        });

        check("decorators stack: syrup on milk on espresso", () -> {
            Beverage b = new Syrup(new Milk(new Espresso()));
            expectEquals("Espresso, milk, syrup", b.description());
            expectEquals(325, b.cents());
        });

        check("the same decorator stacks on itself (double milk)", () -> {
            Beverage b = new Milk(new Milk(new Espresso()));
            expectEquals("Espresso, milk, milk", b.description());
            expectEquals(300, b.cents());
        });

        System.out.println("\n-- CP3: Strategy --");

        check("no-discount strategy leaves the price alone", () ->
            expectEquals(500, new NoDiscount().applyTo(500)));

        check("percent-off strategy takes its cut", () ->
            expectEquals(400, new PercentOff(20).applyTo(500)));

        check("half-off takes half", () ->
            expectEquals(150, new PercentOff(50).applyTo(300)));

        check("strategy prices a decorated drink (20% off a milky espresso)", () ->
            expectEquals(200, new PercentOff(20).applyTo(new Milk(new Espresso()).cents())));

        System.out.println("\n-- CP4: Observer --");

        check("an order notifies a subscribed observer", () -> {
            Counter counter = new Counter();
            SalesTotal sales = new SalesTotal();
            counter.subscribe(sales);
            counter.placeOrder(new Espresso(), new NoDiscount());
            expectEquals(200, sales.totalCents());
        });

        check("every subscriber is notified, and totals accumulate", () -> {
            Counter counter = new Counter();
            SalesTotal sales = new SalesTotal();
            ReceiptPrinter receipt = new ReceiptPrinter();
            counter.subscribe(sales);
            counter.subscribe(receipt);
            counter.placeOrder(new Milk(new Espresso()), new NoDiscount());   // 250
            counter.placeOrder(new Tea(), new PercentOff(20));                // 120
            expectEquals(370, sales.totalCents());
            expectEquals("Tea = 120c", receipt.lastReceipt());
        });

        check("placeOrder charges the discounted total (decorator + strategy + observer together)", () -> {
            Counter counter = new Counter();
            SalesTotal sales = new SalesTotal();
            counter.subscribe(sales);
            int charged = counter.placeOrder(new Syrup(new Milk(new Espresso())), new PercentOff(20)); // 325 -> 260
            expectEquals(260, charged);
            expectEquals(260, sales.totalCents());
        });

        check("a counter with no subscribers still prices the order", () -> {
            int charged = new Counter().placeOrder(new Tea(), new NoDiscount());
            expectEquals(150, charged);
        });

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        if (failed > 0) System.exit(1);
    }

    // --- a tiny test harness. No JUnit, no Maven, nothing to download. ---------------------
    interface Body { void run() throws Throwable; }
    static int passed = 0, failed = 0;

    static void check(String name, Body body) {
        try {
            body.run();
            passed++;
            System.out.println("  PASS  " + name);
        } catch (Throwable t) {
            failed++;
            System.out.println("  FAIL  " + name + "  ->  " + t);
        }
    }

    static void expectEquals(Object expected, Object actual) {
        if (!Objects.equals(expected, actual))
            throw new AssertionError("expected [" + expected + "] but was [" + actual + "]");
    }

    static void expectThrows(Class<? extends Throwable> type, Body body) {
        try {
            body.run();
        } catch (Throwable t) {
            if (type.isInstance(t)) return;
            throw new AssertionError("expected " + type.getSimpleName() + " but threw " + t);
        }
        throw new AssertionError("expected " + type.getSimpleName() + " but nothing was thrown");
    }
}
